---
elastic:
  container_name: 'elastic'
  version: '5.4.1'
#  image_name: "elastic:5.4.1"
  image_name: "docker.elastic.co/elasticsearch/elasticsearch:5.4.1"
  port1: 9200
  port2: 9300
  root_user: '???'

docker:
  network_name: 'elk'
  ips:
    subnet: '172.18.1.0/24'
    gateway: '172.18.1.254'
    ip: '172.18.1.10'
...