---
app:
  version: '5.4.1'
  image_name: 'docker.elastic.co/kibana/kibana:5.4.1'
  user: "{{ansible_user}}"
  group: "{{ansible_user}}"
  container:
    name: 'kibana'
    volumes:
      - "/opt/cluster/kibana/config/:/usr/share/kibana/config"
    network:
      name: 'elk'
      subnet: '172.18.1.0/24'
      gateway: '172.18.1.254'
      ip: '172.18.1.30'
      ports:
        - 5601
#    env:
#      - "ES_JAVA_OPTS: -Xmx256m -Xms256m"
  dirs:
    parent: '/opt/cluster/kibana'
    config: '/opt/cluster/kibana/config'
templates:
  - {template: "kibana.yml.j2", dest: "{{app.dirs.config}}/kibana.yml"}
...