---
kibana:
  container_name: 'kibana'
  version: '5.4.1'
#  image_name: 'kibana:5.4.1'
  image_name: 'docker.elastic.co/kibana/kibana:5.4.1'
#  image_name: 'kibana'
  port1: '5601'
#  port2: 9300
  root_user: '???'

docker:
  network_name: 'elk'
  ips:
    subnet: '172.18.1.0/24'
    gateway: '172.18.1.254'
    ip: '172.18.1.30'

app:
  port:
  name:
  dirs:

...