---
logstash:
  container_name: 'logstash'
#  version: '5.4.1'
  image_name: "docker.elastic.co/logstash/logstash:5.4.1"
  port1: 5000
  root_user: '???'

docker:
  network_name: 'elk'
  ips:
    subnet: '172.18.1.0/24'
    gateway: '172.18.1.254'
    ip: '172.18.1.20'
...