---
# file: use-apt.yml
# Install Oracle JDK 1.x on Debian.
#
# Adapted from: http://www.webupd8.org/2012/06/how-to-install-oracle-java-7-in-debian.html
# See also: http://d.stavrovski.net/blog/post/installing-oracle-java-7-on-debian-wheezy
#


#=============================#
# Oracle Java via WebUpd8
#

- name: Import WebUpd8 PGP key
  apt_key: keyserver=keyserver.ubuntu.com id=0xEEA14886 state=present

- name: add the WebUpd8 Oracle Java PPA repository (for Ubuntu)
  apt_repository: repo=ppa:webupd8team/java state=present
  when: ansible_distribution == "Ubuntu"

- name: add the WebUpd8 Oracle Java PPA repository (for Debian)
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" state=present
  when: ansible_distribution == "Debian"

- name: add the WebUpd8 Oracle Java PPA repository (for Debian)
  apt_repository: repo="deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" state=present
  when: ansible_distribution == "Debian"




- name: automatically accept the Oracle license
  debconf: name="oracle-java{{ java_version }}-installer" question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: install JDK
  apt: pkg="oracle-java{{ java_version }}-installer" state=present force=yes

- name: set this as default Java; also environment variables
  apt: pkg="oracle-java{{ java_version }}-set-default" state=present force=yes
