---
- hosts: elasticsearch
  become: True
  roles:
    - common
    - docker
    - elk

- hosts: logstash
  become: True
  roles:
#    - cogitmmon
#    - docker
    - elk

- hosts: kibana
  become: True
  roles:
#    - common
#    - docker
    - elk
...