---
- hosts: elasticsearch
  become: True
  roles:
#    - common
#    - docker
    - docker_config
    - elasticsearch

- hosts: logstash
  become: True
  roles:
    - logstash

- hosts: kibana
  become: True
  roles:
    - kibana
...