---
- name: Debug
  debug: var=group_names

- name: Creating directories
  become: True
  file: >
      path={{app.dirs[item]}}
      state=directory
      owner={{app.user}}
      group={{app.group}}
      mode="u+rwx,g+rwx"
      recurse=yes
  with_items: "{{app.dirs}}"

- name: Create a network
  become: True
  docker_network:
    name: '{{app.containers.network.name}}'
    ipam_options:
      subnet: '{{app.containers.network.subnet}}'
      gateway: '{{app.containers.network.gateway}}'

- name: Change config files.
  become: True
  template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
    owner: "{{ app.user }}"
    group: "{{ app.group }}"
    mode: 0644
  with_items: "{{ templates }}"
  tags:
    - update_configs

- name: Starting containers.
  become: True
  docker_container:
    name: "{{ app.containers.name }}"
    image: "{{ app.image_name }}"
    state: "started"
    restart_policy: 'always'
    recreate: yes
    volumes: "{{ app.containers.volumes }}"
    networks:
      - name: "{{ app.containers.network.name }}"
        ipv4_address: "{{ app.containers.network.ip }}"
    published_ports: "{{ app.containers.network.ports }}"
    env: "{{ app.containers.env }}"

...
