---
- name: Install epel repository
  become: True
  yum:  name="epel-release" state=latest

- name: Installing PIP
  become: True
  yum: >
        name={{item}}
        state=present
  with_items:
    - 'python-pip'

- name: Installing nessary librarys
  become: True
  pip: >
        name={{item}}
        state=present
  with_items:
   - 'kafka-python'
   - 'pyyaml'

- name: Creating directories
  become: True
  file: >
        path={{app.dirs[item]}}/
        state=directory
        owner={{app.user}}
        group={{app.group}}
        mode="u+rwx,g+rwx"
        recurse=yes
  with_items: '{{app.dirs}}'

- name: Installing Log_agent
  copy: >
        src={{item.file}}
        dest={{app.dirs.home}}/{{item.file}}
  with_items:
    - {file: 'log_agent.py'}
#    - {file: 'config.yaml'}

- name: Coping templates
  become: True
  template: src={{item.template}}
            dest={{item.dest}}
            owner={{app.user}}
            group={{app.group}}
  with_items: "{{templates}}"
  notify:
    - restart_log_agent

- name: Making symbolic link
  become: yes
  file: src={{app.dirs.init_d}}/{{app.name}}
        dest=/etc/init.d/{{app.name}}
        state=link

- name: chkconfig --add {{app.name}}
  become: yes
  shell: chkconfig --add {{app.name}}

- name: Starting log_agent service
  become: True
  service: >
        name={{app.name}}
        state=started
        enabled=yes

...
