---
# tasks file for common



- name: Update all packages
  become: yes
  yum:  name=* state=latest

    #http://www.cyberciti.biz/faq/installing-rhel-epel-repo-on-centos-redhat-7-x/
    # Install EPEL Repo on a CentOS and RHEL 7.x for htop
- name: Install pip
  yum:  name="epel-release" state=latest update_cache=yes cache_valid_time=3600

- name: Install packages
  become: yes
  yum:  name={{ item }} state=latest 
  with_items: 
      - git
      - libselinux-python
      - mc
      - htop
      - vim
  ignore_errors: yes


- name: check if swap exitst
  stat: path={{ swap_file_path }}
  register: swap_exitst


#https://raymii.org/s/tutorials/Ansible_-_Only_if_a_file_exists_or_does_not_exist.html  
- include: swap.yml
  when: swap_exitst.stat.exists == False and make_swap
  


