---
- name: Creating directories
  become: True
  file: >
      path={{item}}/
      state=directory
      owner={{elk.user}}
      group={{elk.group}}
      mode="u+rwx,g+rwx"
      recurse=yes
  with_items:
      - "{{app.dirs.data}}"
      - "{{app.dirs.config}}"
      - "{{app.dirs.config}}"
      - "{{app.dirs.config}}"
      - "{{app.dirs.pipeline}}"


- name: Create a network
  become: True
  docker_network:
    name: '{{docker.network_name}}'
    ipam_options:
      subnet: '{{docker.ips.subnet}}'
      gateway: '{{docker.ips.gateway}}'

#  tags:
#    - pg_config
...